### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hasumikin** [picoruby/picoruby#6]
## mruby integration
- [x] #104

## indispensable
- [x] fcall w/o arg
- [x] fcall w/ multiple args
- [x] $gvar
- [x] @ivar
- [x] CONSTANT
- [x] recv.method
- [x] recv.method.chain
- [x] recv[]
- [x] +, -, *, /, %
- [x] (1 + 2) * 3
- [x] **
- [x] +=, -=, *=, /=, %=, &=, |=, ^=
- [x] **=, <<=, >>=
- [x] [0, 1, "Hello", :symbol] #=> Array
- [x] {a: 0, "key" => :value} #=> Hash
- [x] begin; end -> primary
- [x] #86 

## mruby3
- [x] OP_LOADI16
- [x] unsigned index for JMP (relative jump)

## simple keywords
- [x] true, false, nil
- [x] return
- [x] self

## particularly important on microcontroller
- [x] !, ~, +, -
- [x] not
- [x] &, |, ^
- [x] <<, >>
- [x] 123e-02
- [x] 0xffff, 0o777, 0b1111

## conditional
- [x] if then elsif else end
- [x] unless then else end
- [x] case when else end
- [x] x ? y : z
- [x] <, >
- [x] ==, !=, <=, >=, ===, <=>
- [x] &&, ||
- [x] &&=, ||=
- [x] and, or
- [x] while, break, next, redo 
- [x] until, break, next, redo
- [x] if modifier
- [x] unless modifier

## syntax sugar
- [x] recv[]=, obj.attr=
- [x] recv[]+=, obj.attr+=
- [x] [1, 2].map(&:to_s)
- [x] %w[], %i[] => Array

## block, lambda
- [x] #98
- [x] break, next, redo in block
- [x] [0,1].each do |var| end
- [x] [0,1].each { |var| }
- [x] `a = 2; [1, 2].each{|i| a = i + a}; puts a` => `5` ...OP_GETUPVAR, OP_SETUPVAR
- [x] ->{ }
- [x] yield

## definition
- [x] def hoge end
- [x] class Klass < Super end
- [x] #91

# method parameters
- [x] mandatory
- [x] opt
- [x] rest
- [x] mandatory2
- [x] #101
- [x] #94
- [x] block

## exception
- [x] #84 

## nice to have
- [x] "concat" "enate" => "concatenate"
- [x] po = "PO"; "inter#{po}lation" => "interPOlation"
- [x] Range
- [x] super
- [x] alias
- [x] #97
- [x] #95
- [x] #99
## Improvements
- [x] #96
- [x] #100
- [x] #103
## should be fixed
- [x] b=3; 2*b+=5
- [x] obj.attr+=
- [x] overriding lvar mistakenly: `a=3;p "#{b=2}#{a+b}"` => `"26"` (should be `"25"`). I may have to gather lvars before making VM code
- [x] escape sequence in STRING ( `"\n".ord` => 10, `p '\n'` prints "\\\\n")
- [x] escape sequence in Integer notation `"\33[2J"`
- [x] 37 01 37 01 67 (double return)
- [x] yy_pop_なんとかで謎のSEGV
- [x] if a = true
         p a
       end
- [x] 10**-2
